laboratorio_ocr:
  experimentos:
    - nome: "Laboratório - OCR"
      icone: "car-front"

    - nome: "Contato em Primeiro Grau"
      icone: "car-front"

    - nome: "Contato em Segundo Grau"
      icone: "emoji-sunglasses"

laboratorio_chatboot:
  experimentos:
    - nome: "Laboratório - CHATBOOT"
      icone: "car-front"

    - nome: "Contato em Primeiro Grau"
      icone: "car-front"    

